spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
#  application:
#    name: ecommerce
#  datasource:
#    url: jdbc:mysql://localhost:3306/ecomm_dev
#    username: root
#    password: X-workZodc@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    #    properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQLDialect
#      ddl-auto: create

logging:
  file:
    name: ../ecommerce/log/Ecomm_log.log
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    net:
      guides: DEBUG
